import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { registerBrowserAccount } from './browser_account_fixture.js';

const target = process.argv[2] || 'http://127.0.0.1:5185/';
if (!['localhost', '127.0.0.1'].includes(new URL(target).hostname)) throw Error('LOCAL_ONLY');
const browser = await chromium.launch({ headless: true }), errors = [];
const a = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const b = await browser.newContext({ viewport: { width: 1280, height: 800 } });
const host = await a.newPage(), peer = await b.newPage();
let passed = 0;
const check = (ok, name) => { assert.ok(ok, name); passed++; console.log(`PASS ${name}`); };
const setup = async page => {
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(target); await page.waitForFunction(() => window.startGame);
  await page.evaluate(async () => {
    const url = performance.getEntriesByType('resource').find(e => new URL(e.name).pathname === '/src/game.js')?.name || '/src/game.js';
    window.reviewGame = await import(url);
  });
};
try {
  await mkdir('artifacts', { recursive: true }); await setup(host);
  check(await host.locator('#home-panel').isVisible() && await host.locator('#race-panel').isHidden(), 'Home and race configuration are separate pages');
  check(await host.locator('.race-hero').evaluate(el => el.clientHeight > innerHeight * .6), 'Hero image occupies most of the initial viewport');
  check(await host.locator('.home-routes').evaluate(el => [...el.children].every((n, i, all) => !i || n.getBoundingClientRect().top >= all[i - 1].getBoundingClientRect().bottom)), 'Main actions are vertically stacked');
  await host.screenshot({ path: 'artifacts/paddock-home-desktop.png' });
  await host.click('#tab-race'); await host.fill('#lapCount', '7'); await host.locator('#lapCount').blur();
  await host.click('#tab-records'); check(await host.locator('#records-panel').isVisible(), 'Records page still renders');
  await host.goBack(); check(await host.locator('#race-panel').isVisible() && await host.inputValue('#lapCount') === '7', 'Browser back restores page without resetting race settings');
  await host.screenshot({ path: 'artifacts/paddock-race-config.png' });
  await host.click('#tab-online');
  check(await host.locator('#online-account-gate').isVisible() && await host.locator('#online-entry').isHidden(), 'Guest sees login gate, not online create/join controls');
  check(await host.locator('#online-dialog').evaluate(el => el.tagName === 'SECTION' && Boolean(el.closest('#menu')) && getComputedStyle(el).position === 'static'), 'Online is a full shell page, not a popup');
  const denied = await host.evaluate(async () => (await fetch('/api/v1/auth/online-ticket', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Quick-Grid-Auth': '1' }, body: '{}' })).status);
  check(denied === 401, 'Anonymous HTTP access cannot obtain an online ticket');
  await host.setViewportSize({ width: 390, height: 844 });
  check(await host.locator('#menu').evaluate(el => el.scrollWidth <= el.clientWidth), 'Online login page has no mobile horizontal overflow');
  await host.screenshot({ path: 'artifacts/paddock-online-mobile.png' });
  await host.setViewportSize({ width: 1440, height: 900 });
  await registerBrowserAccount(host, 'Host de Teste'); await setup(peer); await registerBrowserAccount(peer, 'Amigo de Teste');
  await host.bringToFront(); await host.click('#tab-online');
  check(await host.inputValue('#online-name') === 'Host de Teste' && await host.locator('#online-name').evaluate(el => el.readOnly), 'Six-character registration unlocks online with the account pilot name');
  await host.setViewportSize({ width: 390, height: 844 });
  check(await host.locator('#menu').evaluate(el => el.scrollWidth <= el.clientWidth), 'Authenticated online entry fits a narrow screen');
  await host.screenshot({ path: 'artifacts/paddock-online-entry-mobile.png' });
  await host.setViewportSize({ width: 1440, height: 900 });
  await host.locator('[data-online-select="online-format"] [data-value="tournament"]').click();
  await host.fill('#online-rounds', '2'); await host.click('#online-create');
  await host.locator('#online-room').waitFor({ state: 'visible' });
  const code = await host.textContent('#online-room-code'); check(/^[A-F0-9]{6}$/.test(code), 'Authenticated host creates a private code');
  await peer.click('#tab-online'); await peer.fill('#online-code', code); await peer.click('#online-join');
  await host.waitForFunction(() => document.getElementById('online-players').children.length === 2);
  check(await peer.locator('#online-start').isDisabled(), 'Only the host can start');
  await host.bringToFront(); await host.screenshot({ path: 'artifacts/paddock-online-lobby.png' });
  await host.setViewportSize({ width: 390, height: 844 });
  check(await host.locator('#menu').evaluate(el => el.scrollWidth <= el.clientWidth), 'Full lobby has no mobile horizontal overflow');
  await host.screenshot({ path: 'artifacts/paddock-lobby-mobile.png' });
  await host.setViewportSize({ width: 1440, height: 900 });
  await host.click('#online-ready'); await peer.click('#online-ready');
  await host.waitForFunction(() => [...document.getElementById('online-players').children].every(el => el.textContent.includes('pronto')));
  await host.click('#online-start'); await host.locator('#online-votes button').first().waitFor({ state: 'visible' });
  const ids = await host.locator('#online-votes button').evaluateAll(nodes => nodes.map(n => n.dataset.trackId));
  check(ids.length === 3 && new Set(ids).size === 3, 'Tournament offers three distinct circuits');
  await peer.waitForFunction(() => document.querySelectorAll('#online-votes button').length === 3);
  check(JSON.stringify(ids) === JSON.stringify(await peer.locator('#online-votes button').evaluateAll(nodes => nodes.map(n => n.dataset.trackId))), 'Both authenticated players see the same ballot');
  await host.screenshot({ path: 'artifacts/paddock-online-vote.png' });
  await host.locator('#online-votes button').first().click();
  await host.waitForFunction(() => document.querySelector('#online-votes button').getAttribute('aria-pressed') === 'true');
  check(await host.locator('#online-votes button').first().evaluate(el => document.activeElement === el), 'Vote acknowledgment preserves keyboard focus');
  await peer.locator('#online-votes button').first().click();
  await host.waitForFunction(() => window.reviewGame.state.racePhase === 'racing', { timeout: 20000 });
  await peer.waitForFunction(() => window.reviewGame.state.racePhase === 'racing');
  await host.bringToFront();
  if (await host.locator('#menu').isVisible()) await host.click('#online-return');
  await host.locator('#gameCanvas').focus(); await host.keyboard.down('w'); await host.keyboard.down('Space');
  await host.waitForFunction(() => window.reviewGame.state.cars[0].getKmh() > 20 && window.reviewGame.state.cars[0].boostCharge < 1);
  check(true, 'Logged-in driver controls real authoritative acceleration and boost');
  await host.keyboard.up('w'); await host.keyboard.up('Space');
  await host.keyboard.press('Escape');
  check(await host.locator('#online-dialog').isVisible() && await host.evaluate(() => !window.reviewGame.state.isPaused && window.reviewGame.state.onlineSession.menuOpen), 'ESC opens the full lobby page without pausing the online race');
  await host.keyboard.down('w');
  check(await host.evaluate(() => !window.reviewGame.state.keys.KeyW), 'Lobby page suppresses driving keys'); await host.keyboard.up('w');
  await host.click('#online-return'); check(await host.locator('#menu').isHidden(), 'Return to track closes the page and restores driving');
  await host.keyboard.press('Escape'); await host.click('#online-leave');
  await peer.bringToFront(); if (await peer.locator('#menu').isHidden()) await peer.keyboard.press('Escape');
  await peer.waitForFunction(() => [...document.getElementById('online-players').children].some(el => el.textContent.includes('Amigo de Teste') && el.textContent.includes('anfitrião')));
  check(true, 'Host migration remains functional');
  await peer.click('#account-open'); await peer.click('#auth-logout'); await peer.click('#auth-guest');
  check(await peer.locator('#online-account-gate').isVisible() && await peer.locator('#online-room').isHidden(), 'Logout leaves the race and restores the account gate');
  await host.bringToFront(); await host.click('#account-open'); await host.click('#auth-logout'); await host.click('#auth-guest');
  await host.route('http://localhost:3001/api/**', route => route.fulfill({ contentType: 'application/json', body: '{}' }));
  await host.click('#tab-race'); await host.fill('#botCount', '1'); await host.click('#start-race');
  await host.waitForFunction(() => window.reviewGame.state.isRunning);
  check(await host.evaluate(() => !window.reviewGame.state.onlineSession), 'Guest offline racing still starts from the real configuration UI');
  // Visual inspection fixture positions a stationary offline car beside an analyzed board.
  const boardInfo = await host.evaluate(async () => {
    const { getBrakingBoards, sampleTrackDistance } = await import('/src/brakingBoards.js');
    const s = window.reviewGame.state, boards = getBrakingBoards(s.trackPath, s.selectedTrackData.trackWidth);
    const board = boards.find(b => b.metres === 100), p = sampleTrackDistance(s.trackPath, board.distance - 15);
    Object.assign(s.cars[0], { x: p.x, y: p.y, angle: p.angle, vx: 0, vy: 0 });
    return { count: boards.length, metres: board.metres };
  });
  await host.waitForTimeout(500); await host.screenshot({ path: 'artifacts/paddock-braking-board.png' });
  check(boardInfo.count > 0 && boardInfo.metres === 100, 'Analyzed boards are available in the actual race renderer');
  await host.keyboard.press('Escape'); check(await host.locator('#session-dialog').isVisible(), 'Offline ESC still pauses normally');
  check(errors.length === 0, `No browser runtime errors: ${errors.join('; ')}`);
  console.log(`${passed} PASSOU | 0 FALHOU`);
} finally { await browser.close(); }
